Done with team section
December-software-project/sort-algo pull request #73
Opened 2020-12-16 13:05 UTC by Ashley-Lau

Sean needs to insert his picture, and Keane can change or resize his picture himself to make the picture clearer.

2020-12-16 17:58 UTC, seanjyjy commented
* Perhaps for Team and How it work section, they can be more centralised, or the text feels too to the right
* For Team, leave more space between Header and content
* Images for team members feels weird

Overall Good Job

2020-12-17 03:40 UTC, keanecjy requested changes
Great work overall. Agree with the points mentioned by @seanjyjy 

Also would like to add that we can perhaps have more space between each section (Home and How it Works, Visualizer and Team)

2020-12-17 03:40 UTC, keanecjy commented on src/howitworks/HowItWorks.js
> +            description="Visualise the algorithm of your choice."
I believe we should use visualize instead to keep consistent with 'Visualizer'

2020-12-17 03:40 UTC, keanecjy commented on src/howitworks/HowItWorks.js
> +            title="2. Select Defaults"
I think `Defaults` may not be quite right? Perhaps it should be configuration / settings?

2020-12-17 03:40 UTC, keanecjy commented on src/howitworks/HowItWorks.js
> +              the algorithm on step at a time with these functions."
Some typos here. 
Should be:
* Replay the entire sorting process or ~~go~~ walk through
              the algorithm ~~on~~ one step at a time with these functions.

2020-12-17 07:02 UTC, Ashley-Lau commented
Resolved the typos and improved on styling

2020-12-17 08:59 UTC, keanecjy approved these changes
LGTM!

2020-12-17 09:00 UTC, merged